# Generated by Django 6.0.7 on 2026-08-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='highlights',
            field=models.TextField(blank=True, help_text='Optional comma-separated or line-separated list of room highlights', null=True),
        ),
        migrations.AlterField(
            model_name='roombaseprice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price (Regular Rate)'),
        ),
        migrations.AlterField(
            model_name='roombaseprice',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional offer price (must be less than Base Price)', max_digits=10, null=True, verbose_name='Discounted Price (Sale Price) (Optional)'),
        ),
    ]
