# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('airport', 'Airport'), ('park', 'National Park / Wildlife Safari'), ('religious', 'Religious / Heritage Site'), ('tourist', 'Tourist Attraction'), ('border', 'Border Point'), ('city', 'Nearby City / Town')], default='tourist', max_length=20)),
                ('distance', models.CharField(help_text='e.g. 15 km or 500 meters', max_length=50)),
                ('travel_time', models.CharField(help_text='e.g. 20 minutes drive or 5 minutes walk', max_length=100)),
                ('maps_url', models.URLField(blank=True, help_text='Google Maps direction link', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('attractions'), validators=[core.utils.ValidateFileSize(2)])),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
