# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('lounge', 'Lounge'), ('private', 'Private Dining'), ('banquet', 'Banquet Menu')], default='restaurant', max_length=20)),
                ('description', models.TextField()),
                ('timings', models.CharField(help_text='e.g. 7:00 AM - 11:00 PM', max_length=100)),
                ('menu_pdf', models.FileField(blank=True, null=True, upload_to='dining/menus/')),
                ('chef_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chef_bio', models.TextField(blank=True, null=True)),
                ('chef_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/chefs'), validators=[core.utils.ValidateFileSize(2)])),
                ('capacity', models.IntegerField(help_text='Guest capacity')),
                ('featured_dishes', models.TextField(blank=True, help_text='Comma-separated list of featured dishes')),
                ('video_url', models.URLField(blank=True, help_text='Virtual tour or venue intro video', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/venues'), validators=[core.utils.ValidateFileSize(2)])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this dining venue is visible on the website')),
            ],
        ),
        migrations.CreateModel(
            name='DiningReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(default=2)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='dining.diningvenue')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
