# Generated by Django 6.0.7 on 2026-07-30 07:06

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(blank=True, help_text='e.g. fa-solid fa-utensils', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dining Category',
                'verbose_name_plural': 'Dining Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default base price in NPR', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('dining/items'), validators=[core.utils.ValidateFileSize(2)])),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback', null=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('is_chef_special', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dining.diningcategory')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dining_items_default', to='settings_manager.currency')),
            ],
            options={
                'verbose_name': 'Dining Item',
                'verbose_name_plural': 'Dining Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DiningItemBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dining_item_base_prices', to='settings_manager.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='dining.diningitem')),
            ],
            options={
                'verbose_name': 'Dining Item Base Price',
                'verbose_name_plural': 'Dining Item Base Prices',
                'unique_together': {('item', 'currency')},
            },
        ),
    ]
