# Generated by Django 6.0.7 on 2026-07-23 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0002_diningcategory_diningitem'),
        ('settings_manager', '0003_alter_hotelsettings_admin_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default base price in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='diningitem',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dining_items_default', to='settings_manager.currency'),
        ),
        migrations.CreateModel(
            name='DiningItemBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dining_item_base_prices', to='settings_manager.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='dining.diningitem')),
            ],
            options={
                'verbose_name': 'Dining Item Base Price',
                'verbose_name_plural': 'Dining Item Base Prices',
                'unique_together': {('item', 'currency')},
            },
        ),
    ]
