# Generated by Django 6.0.7 on 2026-07-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0003_alter_diningitem_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningreservation',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='diningitem',
            name='venue',
        ),
        migrations.DeleteModel(
            name='DiningVenue',
        ),
    ]
