# Generated by Django 6.0.7 on 2026-07-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0004_remove_diningreservation_venue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiningReservation',
        ),
    ]
