# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this gallery category is visible on the website')),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('gallery'), validators=[core.utils.ValidateFileSize(2)])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_video', models.BooleanField(default=False)),
                ('is_drone', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', null=True)),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Virtual tour embed link', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this gallery item is visible on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gallery.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
