# Generated by Django 6.0.7 on 2026-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('maps_iframe', models.TextField(blank=True, help_text='Google Maps iframe embed code', null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this branch is visible on the website')),
            ],
            options={
                'verbose_name': 'Hotel Branch',
                'verbose_name_plural': 'Hotel Branches',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('room', 'Room Booking Inquiry'), ('event', 'Event & Banquets Inquiry'), ('dining', 'Dining & Table Booking')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
