# Generated by Django 6.0.7 on 2026-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email ownership verified via double opt-in'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Active subscriber status'),
        ),
    ]
