# Generated by Django 6.0.7 on 2026-07-21 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.IntegerField(default=2)),
                ('children', models.IntegerField(default=0)),
                ('num_rooms', models.PositiveIntegerField(default=1, help_text='Number of rooms booked')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='USD', help_text='Currency ISO code used when booking was created', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('channel_name', models.CharField(default='direct', help_text='e.g. direct, booking.com, expedia, agoda', max_length=50)),
                ('ota_reservation_id', models.CharField(blank=True, help_text='Reservation ID from the OTA/channel manager', max_length=100, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('card', 'Visa/Mastercard'), ('pay_later', 'Pay at Hotel')], default='pay_later', max_length=50)),
                ('channel_raw_payload', models.JSONField(blank=True, help_text='Raw payload received from the channel manager/OTA API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount ($)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
