# Generated by Django 6.0.7 on 2026-07-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('room', 'Room Booking'), ('zipline', 'Zipline Package')], default='room', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_date',
            field=models.DateField(blank=True, help_text='Date for Zipline flight', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_tickets',
            field=models.PositiveIntegerField(default=1, help_text='Number of zipline flights / people'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_time',
            field=models.CharField(blank=True, help_text='Preferred time slot e.g. 10:00 AM', max_length=50, null=True),
        ),
    ]
