# Generated by Django 6.0.7 on 2026-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='waiver_accepted',
            field=models.BooleanField(default=False, help_text='Whether guest agreed to NAGARKOT ZIPLINE PVT. LTD Waiver & Release of Liability Form'),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiver_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when waiver consent was given', null=True),
        ),
    ]
