# Generated by Django 6.0.7 on 2026-07-29 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_zipline_package_alter_booking_check_in_and_more'),
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products (Rooms & Zipline)'), ('room', 'Room Stays Only'), ('zipline', 'Zipline Flights Only')], default='all', help_text='Specify product type this discount applies to', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Specific currency for min spend & fixed discount (leave empty for any currency)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_manager.currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_spend',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order spend required to redeem this coupon', max_digits=10),
        ),
    ]
