# Generated by Django 6.0.7 on 2026-07-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_coupon_applicable_to_coupon_currency_and_more'),
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-id'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_spend',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, help_text='Internal note about this coupon (not shown to guests)', max_length=200),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be redeemed. Leave empty for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='use_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this coupon has been redeemed (auto-tracked).'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Products (Rooms & Zipline)'), ('room', 'Room Stays Only'), ('zipline', 'Zipline Flights Only')], default='all', help_text='Restrict this coupon to a specific product type', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount (in selected currency)')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text="For percentage: enter 10 for 10%. For fixed: enter the amount in the guest's currency.", max_digits=10),
        ),
        migrations.CreateModel(
            name='CouponMinSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value in this currency to apply the coupon', max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min_spends', to='booking.coupon')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_min_spends', to='settings_manager.currency')),
            ],
            options={
                'verbose_name': 'Coupon Min Spend',
                'verbose_name_plural': 'Coupon Min Spends',
                'unique_together': {('coupon', 'currency')},
            },
        ),
    ]
