# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Prem Durbar', max_length=150)),
                ('subtitle', models.CharField(default='A Haven of Luxury & Hospitality', max_length=250)),
                ('content', models.TextField(help_text='Introductory text about the hotel')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/about'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='Promo video YouTube/Vimeo link', null=True)),
                ('stat1_value', models.CharField(default='120', max_length=10)),
                ('stat1_label', models.CharField(default='Luxury Rooms', max_length=50)),
                ('stat2_value', models.CharField(default='5', max_length=10)),
                ('stat2_label', models.CharField(default='Star Rating', max_length=50)),
                ('stat3_value', models.CharField(default='3', max_length=10)),
                ('stat3_label', models.CharField(default='Elite Restaurants', max_length=50)),
                ('stat4_value', models.CharField(default='15+', max_length=10)),
                ('stat4_label', models.CharField(default='Awards Won', max_length=50)),
            ],
            options={
                'verbose_name': 'Homepage About Preview',
                'verbose_name_plural': 'Homepage About Preview',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/hero'), validators=[core.utils.ValidateFileSize(2)])),
                ('background_video_url', models.URLField(blank=True, help_text='YouTube or direct MP4 link', null=True)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Dark overlay opacity (0.00 to 1.00)', max_digits=3)),
                ('cta_text', models.CharField(default='Discover More', max_length=50)),
                ('cta_url', models.CharField(default='/rooms/', max_length=200)),
                ('cta2_text', models.CharField(blank=True, default='Book Now', max_length=50, null=True)),
                ('cta2_url', models.CharField(blank=True, default='/booking/', max_length=200, null=True)),
                ('title_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInDown', max_length=50)),
                ('subtitle_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInUp', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
