# Generated by Django 6.0.7 on 2026-07-27 05:33

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Heritage & Mountain Hospitality', max_length=150)),
                ('hero_title', models.CharField(default='Our Story & Legacy', max_length=150)),
                ('hero_description', models.TextField(default='Nestled in Changunarayan-7, Nagarkot, Prem Durbar blends authentic Newari brick & wood craftsmanship with mountain tranquility, organic gastronomy, and high-altitude adventure.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_subtitle', models.CharField(default='Kathmandu Valley Artistry', max_length=150)),
                ('story_title', models.CharField(default='Traditional Newari Architecture Meets Mountain Luxury', max_length=200)),
                ('story_content', models.TextField(default="Prem Durbar was envisioned as a living tribute to Nepal's rich architectural heritage. Every brick, carved wood wooden struts, and terracotta tile was handcrafted by local artisans from Bhaktapur and Kathmandu Valley. Overlooking the serene Kamal Pokhari pond and pine forest ridge, our resort offers guests an immersive journey into Nepalese royal durbar elegance combined with modern five-star comfort.")),
                ('story_extra', models.TextField(blank=True, default='Overlooking the peaceful Kamal Pokhari (Lotus Pond) and surrounded by Nagarkot’s lush pine forests, our resort offers guests a tranquil retreat from urban life while keeping you connected to organic nature and panoramic Himalayan vistas.')),
                ('badge1_title', models.CharField(default='Handcrafted Decor', max_length=100)),
                ('badge1_desc', models.CharField(default='Reclaimed wood beds & carved Newari window art.', max_length=200)),
                ('badge2_title', models.CharField(default='Himalayan Panorama', max_length=100)),
                ('badge2_desc', models.CharField(default='Unobstructed sunrise & sunset mountain views.', max_length=200)),
                ('story_image1', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_image2', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_image3', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_image4', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL for resort tour', null=True)),
                ('zipline_callout_title', models.CharField(default='Nagarkot Zipline — The Superman Zip Line', max_length=200)),
                ('zipline_callout_desc', models.TextField(default='Prem Durbar is proud home to Nepal’s longest, safest, and most thrill-inducing Superman Zipline. Soar through Nagarkot’s pine-clad hills with breathtaking views of Mount Everest and the Himalayan range.')),
                ('zipline_callout_link_text', models.CharField(default='Explore Zipline Flight', max_length=100)),
                ('team_subtitle', models.CharField(default='Passionate Hospitality Professionals', max_length=150)),
                ('team_title', models.CharField(default='Meet Our Executive Leadership', max_length=200)),
            ],
            options={
                'verbose_name': 'About Page Content CMS',
                'verbose_name_plural': 'About Page Content CMS',
            },
        ),
        migrations.CreateModel(
            name='AboutPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Resort', max_length=150)),
                ('subtitle', models.CharField(default='A Haven of Luxury & Hospitality', max_length=250)),
                ('content', models.TextField(help_text='Introductory text about the hotel')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/about'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='Promo video YouTube/Vimeo link', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file to play on the homepage', null=True, upload_to=core.utils.UploadTo('homepage/videos'))),
                ('stat1_value', models.CharField(default='120', max_length=10)),
                ('stat1_label', models.CharField(default='Luxury Rooms', max_length=50)),
                ('stat2_value', models.CharField(default='5', max_length=10)),
                ('stat2_label', models.CharField(default='Star Rating', max_length=50)),
                ('stat3_value', models.CharField(default='3', max_length=10)),
                ('stat3_label', models.CharField(default='Elite Restaurants', max_length=50)),
                ('stat4_value', models.CharField(default='15+', max_length=10)),
                ('stat4_label', models.CharField(default='Awards Won', max_length=50)),
            ],
            options={
                'verbose_name': 'Homepage About Preview',
                'verbose_name_plural': 'Homepage About Preview',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('homepage/hero'), validators=[core.utils.ValidateFileSize(2)])),
                ('background_video_url', models.URLField(blank=True, help_text='YouTube or direct MP4 link', null=True)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Dark overlay opacity (0.00 to 1.00)', max_digits=3)),
                ('cta_text', models.CharField(default='Discover More', max_length=50)),
                ('cta_url', models.CharField(default='/rooms/', max_length=200)),
                ('cta2_text', models.CharField(blank=True, default='Book Now', max_length=50, null=True)),
                ('cta2_url', models.CharField(blank=True, default='/booking/', max_length=200, null=True)),
                ('title_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInDown', max_length=50)),
                ('subtitle_animation', models.CharField(choices=[('fadeInDown', 'Fade In Down'), ('fadeInUp', 'Fade In Up'), ('zoomIn', 'Zoom In'), ('slideInLeft', 'Slide In Left'), ('slideInRight', 'Slide In Right')], default='fadeInUp', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SustainabilityCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Responsible Hospitality', max_length=150)),
                ('hero_title', models.CharField(default='Eco-Sustainability & Local Empowerment', max_length=150)),
                ('hero_description', models.TextField(default='Preserving Nagarkot’s natural pine beauty and supporting local mountain communities while providing luxurious guest comfort.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('sustainability/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('intro_subtitle', models.CharField(default='Pillars of Action', max_length=150)),
                ('intro_title', models.CharField(default='Our Environmental & Community Commitments', max_length=200)),
            ],
            options={
                'verbose_name': 'Sustainability Page Content CMS',
                'verbose_name_plural': 'Sustainability Page Content CMS',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-solar-panel', help_text='FontAwesome icon, e.g. fa-solid fa-leaf', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sustainability Pillar',
                'verbose_name_plural': 'Sustainability Pillars',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('team/members'), validators=[core.utils.ValidateFileSize(2)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on About Us page')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ZiplineCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Nagarkot Adventure Destination', max_length=150)),
                ('hero_title', models.CharField(default='Nagarkot Zipline: The Superman Zip Line', max_length=150)),
                ('hero_description', models.TextField(default='Soar through the skies of Nagarkot above lush pine forests with panoramic views of the Himalayan range and Mount Everest.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('zipline/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or external MP4 URL for Zipline video preview', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file to play on the Zipline page', null=True, upload_to=core.utils.UploadTo('zipline/videos'))),
                ('spec_length', models.CharField(default='1,200 Meters', max_length=50)),
                ('spec_length_label', models.CharField(default='Flight Length', max_length=50)),
                ('spec_speed', models.CharField(default='95 KM/H', max_length=50)),
                ('spec_speed_label', models.CharField(default='Top Speed', max_length=50)),
                ('spec_elevation', models.CharField(default='2,175m Altitude', max_length=50)),
                ('spec_elevation_label', models.CharField(default='Altitude Elevation', max_length=50)),
                ('spec_safety', models.CharField(default='100% International Certified', max_length=50)),
                ('spec_safety_label', models.CharField(default='Safety Standard', max_length=50)),
                ('booking_url', models.URLField(default='https://www.facebook.com/ziplinenagarkot', help_text='External URL for booking zipline (e.g. Facebook page or booking engine)')),
                ('booking_button_text', models.CharField(default='Book Zipline Flight / Facebook Page', max_length=100)),
                ('overview_subtitle', models.CharField(default='High-Altitude Thrill', max_length=150)),
                ('overview_title', models.CharField(default="Nepal's Longest Superman Flight Zipline", max_length=200)),
                ('overview_content', models.TextField(default="Located just 32 kilometers from Kathmandu at Changunarayan-7, Nagarkot, Nagarkot Zipline offers one of South Asia's most thrilling high-altitude zipline experiences. Choose between Superman Flight position, Tandem dual flight, or Classic harness zip as you glide above pine forests facing snow-capped peaks.")),
                ('overview_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('zipline/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('image_caption_title', models.CharField(default='Superman Flying Harness', max_length=100)),
                ('image_caption_subtitle', models.CharField(default='Head-first aerial view of Everest range', max_length=150)),
            ],
            options={
                'verbose_name': 'Zipline Page Content CMS',
                'verbose_name_plural': 'Zipline Page Content CMS',
            },
        ),
    ]
