# Generated by Django 6.0.7 on 2026-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziplinecms',
            name='available_time_slots',
            field=models.TextField(default='Morning (09:00 AM - 12:00 PM)\nAfternoon (12:00 PM - 03:00 PM)\nSunset Flight (03:00 PM - 06:00 PM)', help_text='Time slots for zipline booking (one slot option per line)'),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='waiver_subtitle',
            field=models.CharField(default='PARTICIPANT USER AGREEMENT', max_length=200),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='waiver_text',
            field=models.TextField(default='In consideration of NAGARKOT ZIPLINE PVT. LTD furnishing services and/or equipment to enable me to participate in activities associated with or enter upon the lands of NAGARKOT ZIPLINE PVT. LTD., their agents, owners, associates and all other persons or entities acting in any capacity on their behalf (hereinafter collectively referred to as "Zip Line Tour"), I hereby voluntarily agree to release, discharge, hold harmless and covenant not to sue Zip Line Tour on behalf of myself, my children, my parents, my heirs, assigns, personal representatives and/or estate for any and all claims of liability arising out of negligence, recklessness, strict liability, breach of contract, intentional acts or any other act or omission which causes illness, injury, death or damage of any nature in any way connected with my participation in this activity.\n\nI fully understand and acknowledge that:\nA. Outdoor recreational activities such as zip lines, canopy tours, challenge courses, mountain hiking and exploring have inherent risks, dangers and hazards, and such risks may exist in my use of NAGARKOT ZIPLINE PVT. LTD. property and equipment.\nB. My participation in such activities and/or use of such equipment may result in injury or illness including, but not limited to, body injury, strains, fractures, partial or total paralysis, death, exposure to insects and snake bites, extreme temperatures, slips and falls, encounters with animals, collisions, and remote area medical limitations.\nC. These risks and dangers may be caused by negligence of the owners, employees, officers or agents of NAGARKOT ZIPLINE PVT. LTD., negligence of participants, accidents, breaches of contract, forces of nature, or other causes, whether foreseeable or unforeseeable.\nD. By participating in these activities, I assume all risks and responsibility for any loss or damage whether caused in whole or in part by negligence or other conduct of NAGARKOT ZIPLINE PVT. LTD. I also grant permission to NAGARKOT ZIPLINE PVT. LTD. to use photographs or recordings for promotional purposes without compensation.\n\nI have read the above and fully understand that by signing this document I am waiving legal rights and confirm that I choose to sign it freely and voluntarily in full knowledge of the risks.', help_text='Full legal terms text displayed inside the Zipline Booking Waiver Modal'),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='waiver_title',
            field=models.CharField(default='WAIVER & RELEASE OF LIABILITY FORM', max_length=200),
        ),
    ]
