# Generated by Django 6.0.7 on 2026-07-23 06:32

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Heritage & Mountain Hospitality', max_length=150)),
                ('hero_title', models.CharField(default='Our Story & Legacy', max_length=150)),
                ('hero_description', models.TextField(default='Nestled in Changunarayan-7, Nagarkot, Prem Durbar blends authentic Newari brick & wood craftsmanship with mountain tranquility, organic gastronomy, and high-altitude adventure.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_subtitle', models.CharField(default='Kathmandu Valley Artistry', max_length=150)),
                ('story_title', models.CharField(default='Traditional Newari Architecture Meets Mountain Luxury', max_length=200)),
                ('story_content', models.TextField(default="Prem Durbar was envisioned as a living tribute to Nepal's rich architectural heritage. Every brick, carved wood wooden struts, and terracotta tile was handcrafted by local artisans from Bhaktapur and Kathmandu Valley. Overlooking the serene Kamal Pokhari pond and pine forest ridge, our resort offers guests an immersive journey into Nepalese royal durbar elegance combined with modern five-star comfort.")),
                ('story_image1', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('story_image2', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL for resort tour', null=True)),
                ('team_subtitle', models.CharField(default='Passionate Hospitality Professionals', max_length=150)),
                ('team_title', models.CharField(default='Meet Our Executive Leadership', max_length=200)),
            ],
            options={
                'verbose_name': 'About Page Content CMS',
                'verbose_name_plural': 'About Page Content CMS',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Responsible Hospitality', max_length=150)),
                ('hero_title', models.CharField(default='Eco-Sustainability & Local Empowerment', max_length=150)),
                ('hero_description', models.TextField(default='Preserving Nagarkot’s natural pine beauty and supporting local mountain communities while providing luxurious guest comfort.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('sustainability/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('intro_subtitle', models.CharField(default='Pillars of Action', max_length=150)),
                ('intro_title', models.CharField(default='Our Environmental & Community Commitments', max_length=200)),
            ],
            options={
                'verbose_name': 'Sustainability Page Content CMS',
                'verbose_name_plural': 'Sustainability Page Content CMS',
            },
        ),
        migrations.CreateModel(
            name='SustainabilityPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fa-solid fa-solar-panel', help_text='FontAwesome icon, e.g. fa-solid fa-leaf', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sustainability Pillar',
                'verbose_name_plural': 'Sustainability Pillars',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ZiplineCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_subtitle', models.CharField(default='Nagarkot Adventure Destination', max_length=150)),
                ('hero_title', models.CharField(default='Nagarkot Zipline: The Superman Zip Line', max_length=150)),
                ('hero_description', models.TextField(default='Soar through the skies of Nagarkot above lush pine forests with panoramic views of the Himalayan range and Mount Everest.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('zipline/cms'), validators=[core.utils.ValidateFileSize(2)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or external MP4 URL for Zipline video preview', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file to play on the Zipline page', null=True, upload_to=core.utils.UploadTo('zipline/videos'))),
                ('spec_length', models.CharField(default='1,200 Meters', max_length=50)),
                ('spec_speed', models.CharField(default='95 KM/H', max_length=50)),
                ('spec_elevation', models.CharField(default='2,175m Altitude', max_length=50)),
                ('spec_safety', models.CharField(default='100% International Certified', max_length=50)),
                ('overview_subtitle', models.CharField(default='High-Altitude Thrill', max_length=150)),
                ('overview_title', models.CharField(default="Nepal's Longest Superman Flight Zipline", max_length=200)),
                ('overview_content', models.TextField(default="Located just 32 kilometers from Kathmandu at Changunarayan-7, Nagarkot, Nagarkot Zipline offers one of South Asia's most thrilling high-altitude zipline experiences. Choose between Superman Flight position, Tandem dual flight, or Classic harness zip as you glide above pine forests facing snow-capped peaks.")),
                ('overview_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('zipline/cms'), validators=[core.utils.ValidateFileSize(2)])),
            ],
            options={
                'verbose_name': 'Zipline Page Content CMS',
                'verbose_name_plural': 'Zipline Page Content CMS',
            },
        ),
        migrations.AlterField(
            model_name='aboutpreview',
            name='title',
            field=models.CharField(default='About Our Resort', max_length=150),
        ),
    ]
