# Generated by Django 6.0.7 on 2026-07-29 07:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiplinePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('highlights', models.TextField(blank=True, help_text='Comma or line separated highlights of this package')),
                ('flight_type', models.CharField(default='Superman Flight', help_text='e.g. Superman, Tandem Dual, Classic Harness', max_length=100)),
                ('duration', models.CharField(default='2 Minutes / 1.2 KM', help_text='Duration or distance specs', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('zipline/packages'), validators=[core.utils.ValidateFileSize(2)])),
                ('image_url', models.URLField(blank=True, help_text='Fallback external image URL', null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zipline Package',
                'verbose_name_plural': 'Zipline Packages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ZiplinePackageBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zipline_package_base_prices', to='settings_manager.currency')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_prices', to='homepage.ziplinepackage')),
            ],
            options={
                'verbose_name': 'Zipline Package Base Price',
                'verbose_name_plural': 'Zipline Package Base Prices',
                'unique_together': {('package', 'currency')},
            },
        ),
    ]
