# Generated by Django 6.0.7 on 2026-07-23 09:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_aboutcms_sustainabilitycms_sustainabilitypillar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpreview',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file to play on the homepage', null=True, upload_to=core.utils.UploadTo('homepage/videos')),
        ),
    ]
