# Generated by Django 6.0.7 on 2026-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_ziplinecms_available_time_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcms',
            name='team_description',
            field=models.TextField(default='Our passionate team ensures your stay in Nagarkot is comfortable, memorable, and safe—from your luxury room to your zipline flight.', help_text='Description under team section title'),
        ),
        migrations.AddField(
            model_name='sustainabilitycms',
            name='callout_btn_text',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sustainabilitycms',
            name='callout_desc',
            field=models.TextField(default='Get in touch with our Nagarkot team for corporate sustainability inquiries.'),
        ),
        migrations.AddField(
            model_name='sustainabilitycms',
            name='callout_title',
            field=models.CharField(default='Have Questions About Our Eco Policies?', max_length=200),
        ),
    ]
