# Generated by Django 6.0.7 on 2026-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_ziplinepackage_ziplinepackagebaseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziplinecms',
            name='homepage_badge_text',
            field=models.CharField(default='2nd Destination • Nagarkot Zipline', help_text='Badge label shown above the heading on the homepage zipline section', max_length=120),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='homepage_description',
            field=models.TextField(default='Soar above lush pine forests facing snow-capped Himalayan peaks. Select a zipline package and book instantly!', help_text='Short description shown under the heading on the homepage zipline section'),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='homepage_heading',
            field=models.CharField(default="Nepal's Longest Zipline Flight", help_text='Main heading for the zipline section on the homepage', max_length=200),
        ),
    ]
