# Generated by Django 6.0.7 on 2026-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_aboutcms_team_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziplinecms',
            name='image_caption_subtitle',
            field=models.CharField(blank=True, default='Head-first aerial view of Everest range', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ziplinecms',
            name='image_caption_title',
            field=models.CharField(blank=True, default='Superman Flying Harness', max_length=100, null=True),
        ),
    ]
