# Generated by Django 6.0.7 on 2026-07-24 07:17

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_aboutpreview_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('team/members'), validators=[core.utils.ValidateFileSize(2)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance on About Us page')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='badge1_desc',
            field=models.CharField(default='Reclaimed wood beds & carved Newari window art.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='badge1_title',
            field=models.CharField(default='Handcrafted Decor', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='badge2_desc',
            field=models.CharField(default='Unobstructed sunrise & sunset mountain views.', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='badge2_title',
            field=models.CharField(default='Himalayan Panorama', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='story_extra',
            field=models.TextField(blank=True, default='Overlooking the peaceful Kamal Pokhari (Lotus Pond) and surrounded by Nagarkot’s lush pine forests, our resort offers guests a tranquil retreat from urban life while keeping you connected to organic nature and panoramic Himalayan vistas.'),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='story_image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='story_image4',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('about/cms'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='zipline_callout_desc',
            field=models.TextField(default='Prem Durbar is proud home to Nepal’s longest, safest, and most thrill-inducing Superman Zipline. Soar through Nagarkot’s pine-clad hills with breathtaking views of Mount Everest and the Himalayan range.'),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='zipline_callout_link_text',
            field=models.CharField(default='Explore Zipline Flight', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutcms',
            name='zipline_callout_title',
            field=models.CharField(default='Nagarkot Zipline — The Superman Zip Line', max_length=200),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='booking_button_text',
            field=models.CharField(default='Book Zipline Flight / Facebook Page', max_length=100),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='booking_url',
            field=models.URLField(default='https://www.facebook.com/ziplinenagarkot', help_text='External URL for booking zipline (e.g. Facebook page or booking engine)'),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='image_caption_subtitle',
            field=models.CharField(default='Head-first aerial view of Everest range', max_length=150),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='image_caption_title',
            field=models.CharField(default='Superman Flying Harness', max_length=100),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='spec_elevation_label',
            field=models.CharField(default='Altitude Elevation', max_length=50),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='spec_length_label',
            field=models.CharField(default='Flight Length', max_length=50),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='spec_safety_label',
            field=models.CharField(default='Safety Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='ziplinecms',
            name='spec_speed_label',
            field=models.CharField(default='Top Speed', max_length=50),
        ),
    ]
