# Generated by Django 6.0.7 on 2026-08-03 06:13

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Prem Durbar', max_length=100)),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon icon (.png, .ico, .svg)', null=True, upload_to=core.utils.UploadTo('settings/favicons'), validators=[core.utils.ValidateFileSize(2)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)])),
                ('logo_dark', models.ImageField(blank=True, help_text='Dark mode logo version', null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)])),
                ('admin_logo', models.ImageField(blank=True, help_text='Admin panel logo (falls back to main logo if blank)', null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)])),
                ('admin_title', models.CharField(default='Prem Durbar CMS Admin Dashboard', help_text='Admin panel browser tab title', max_length=100)),
                ('admin_label', models.CharField(default='Prem Durbar Portal', help_text='Admin sidebar header label', max_length=100)),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('luxury', 'Luxury Gold Mode'), ('festival', 'Festival Theme')], default='luxury', max_length=20)),
                ('contact_phone', models.CharField(default='+977-015145351, +977-9851160380', max_length=50)),
                ('contact_email', models.EmailField(default='info@premdurbar.com', max_length=254)),
                ('address', models.CharField(default='Nagarkot, Nepal', max_length=255)),
                ('vat_no', models.CharField(default='609554676', help_text='Company VAT/PAN Registration Number', max_length=50)),
                ('zipline_company_name', models.CharField(default='NAGARKOT ZIPLINE PVT. LTD', help_text='Official registered name of zipline company', max_length=150)),
                ('zipline_address', models.CharField(default='Chagunarayan-07, Bhaktapur, Nepal', help_text='Registered address of zipline company', max_length=255)),
                ('zipline_phone', models.CharField(default='+977-015145351, +977-9851160380', help_text='Official zipline contact phone numbers', max_length=100)),
                ('google_maps_iframe', models.TextField(blank=True, help_text='Google Maps HTML embed iframe', null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('tripadvisor_url', models.URLField(blank=True, null=True)),
                ('header_cta_text', models.CharField(default='Book A Stay', help_text='Text shown on header CTA button', max_length=100)),
                ('header_cta_url', models.CharField(default='/rooms/', help_text='Link URL for header CTA button', max_length=255)),
                ('about_text', models.TextField(default='A premium 5-star experience of hospitality and luxury.')),
                ('copyright_text', models.CharField(default='&copy; 2026 Prem Durbar. All Rights Reserved.', max_length=255)),
                ('footer_awards_text', models.CharField(default='Powered by PocketSoft Pvt Ltd', help_text='Footer credits badge text (e.g. Powered by PocketSoft Pvt Ltd)', max_length=255)),
                ('footer_credits_url', models.CharField(blank=True, default='', help_text='Link URL for footer credits badge (optional)', max_length=255, null=True)),
                ('footer_show_visa', models.BooleanField(default=True, help_text='Display Visa logo in footer')),
                ('footer_show_mastercard', models.BooleanField(default=True, help_text='Display Mastercard logo in footer')),
                ('footer_show_stripe', models.BooleanField(default=True, help_text='Display Stripe logo in footer')),
                ('footer_show_esewa', models.BooleanField(default=True, help_text='Display eSewa logo in footer')),
                ('footer_show_khalti', models.BooleanField(default=True, help_text='Display Khalti logo in footer')),
                ('mobile_menu_cta_text', models.CharField(default='Book A Stay', help_text='Text shown on mobile menu CTA button', max_length=100)),
                ('mobile_menu_cta_url', models.CharField(default='/rooms/', help_text='Link URL for mobile menu CTA button', max_length=255)),
                ('search_modal_title', models.CharField(default='Search Resort', help_text='Title shown in search overlay modal', max_length=150)),
                ('search_modal_placeholder', models.CharField(default='Search room categories, dining, amenities...', help_text='Placeholder text in search input', max_length=255)),
                ('search_modal_button_text', models.CharField(default='Search', help_text='Button text in search modal', max_length=50)),
                ('rooms_section_subtitle', models.CharField(default='Premium Sanctuary', max_length=150)),
                ('rooms_section_title', models.CharField(default='Rooms & Suites', max_length=150)),
                ('rooms_section_desc', models.TextField(default='Explore our signature guest chambers designed for ultimate relaxation and comfort.')),
                ('facilities_section_subtitle', models.CharField(default='Elite Hospitality', max_length=150)),
                ('facilities_section_title', models.CharField(default='Resort Services & Facilities', max_length=150)),
                ('facilities_section_desc', models.TextField(default='Indulge in our carefully curated amenities, designed to elevate your stay to a world-class level.')),
                ('testimonials_section_subtitle', models.CharField(default='Guest Memoirs', max_length=150)),
                ('testimonials_section_title', models.CharField(default='What Our Guests Say', max_length=150)),
                ('newsletter_section_subtitle', models.CharField(default='Newsletter Subscription', max_length=150)),
                ('newsletter_section_title', models.CharField(default='Join The Elite Guild', max_length=150)),
                ('newsletter_section_desc', models.TextField(default='Subscribe to receive exclusive offers, luxury travel logs, seasonal booking discounts, and resort news.')),
                ('newsletter_btn_text', models.CharField(default='Subscribe', max_length=50)),
            ],
            options={
                'verbose_name': 'Hotel Global Settings',
                'verbose_name_plural': 'Hotel Global Settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(help_text='e.g. /rooms/ or https://booking.com', max_length=200)),
                ('position', models.CharField(choices=[('header', 'Header Main Navigation'), ('footer_links', 'Footer Quick Links'), ('footer_services', 'Footer Our Services'), ('footer_ota', 'Footer OTA Partners')], default='header', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this menu item is visible on the website')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='settings_manager.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('iso_code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('sequence', models.SmallIntegerField(null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('display_name', models.GeneratedField(db_persist=True, expression=models.F('name'), output_field=models.CharField(max_length=128))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'indexes': [models.Index(fields=['iso_code'], name='settings_ma_iso_cod_695d7c_idx')],
            },
        ),
    ]
