# Generated by Django 6.0.7 on 2026-07-22 06:07

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='admin_label',
            field=models.CharField(default='Ichchha Portal', help_text='Admin sidebar header label', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='admin_logo',
            field=models.ImageField(blank=True, help_text='Admin panel logo (falls back to main logo if blank)', null=True, upload_to=core.utils.UploadTo('settings/logos'), validators=[core.utils.ValidateFileSize(2)]),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='admin_title',
            field=models.CharField(default='Hotel Ichchha CMS Admin Dashboard', help_text='Admin panel browser tab title', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser favicon icon (.png, .ico, .svg)', null=True, upload_to=core.utils.UploadTo('settings/favicons'), validators=[core.utils.ValidateFileSize(2)]),
        ),
    ]
