# Generated by Django 6.0.7 on 2026-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='vat_no',
            field=models.CharField(default='609554676', help_text='Company VAT/PAN Registration Number', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='zipline_address',
            field=models.CharField(default='Chagunarayan-07, Bhaktapur, Nepal', help_text='Registered address of zipline company', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='zipline_company_name',
            field=models.CharField(default='NAGARKOT ZIPLINE PVT. LTD', help_text='Official registered name of zipline company', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='zipline_phone',
            field=models.CharField(default='+977-015145351, +977-9851160380', help_text='Official zipline contact phone numbers', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='contact_phone',
            field=models.CharField(default='+977-015145351, +977-9851160380', max_length=50),
        ),
    ]
