# Generated by Django 6.0.7 on 2026-07-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_hotelsettings_vat_no_hotelsettings_zipline_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_awards_text',
            field=models.CharField(default='Awards: World Luxury Hotel Winner 2026', help_text='Footer awards badge text', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_show_esewa',
            field=models.BooleanField(default=True, help_text='Display eSewa logo in footer'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_show_khalti',
            field=models.BooleanField(default=True, help_text='Display Khalti logo in footer'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_show_mastercard',
            field=models.BooleanField(default=True, help_text='Display Mastercard logo in footer'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_show_stripe',
            field=models.BooleanField(default=True, help_text='Display Stripe logo in footer'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_show_visa',
            field=models.BooleanField(default=True, help_text='Display Visa logo in footer'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='header_cta_text',
            field=models.CharField(default='Book A Stay', help_text='Text shown on header CTA button', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='header_cta_url',
            field=models.CharField(default='/rooms/', help_text='Link URL for header CTA button', max_length=255),
        ),
    ]
