# Generated by Django 6.0.7 on 2026-07-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_hotelsettings_admin_label_hotelsettings_admin_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsettings',
            name='admin_title',
            field=models.CharField(default='Prem Durbar CMS Admin Dashboard', help_text='Admin panel browser tab title', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='copyright_text',
            field=models.CharField(default='&copy; 2026 Prem Durbar. All Rights Reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='site_name',
            field=models.CharField(default='Prem Durbar', max_length=100),
        ),
    ]
