# Generated by Django 6.0.7 on 2026-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0003_hotelsettings_footer_awards_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='facilities_section_desc',
            field=models.TextField(default='Indulge in our carefully curated amenities, designed to elevate your stay to a world-class level.'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='facilities_section_subtitle',
            field=models.CharField(default='Elite Hospitality', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='facilities_section_title',
            field=models.CharField(default='Resort Services & Facilities', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='mobile_menu_cta_text',
            field=models.CharField(default='Book A Stay', help_text='Text shown on mobile menu CTA button', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='mobile_menu_cta_url',
            field=models.CharField(default='/rooms/', help_text='Link URL for mobile menu CTA button', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='newsletter_btn_text',
            field=models.CharField(default='Subscribe', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='newsletter_section_desc',
            field=models.TextField(default='Subscribe to receive exclusive offers, luxury travel logs, seasonal booking discounts, and resort news.'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='newsletter_section_subtitle',
            field=models.CharField(default='Newsletter Subscription', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='newsletter_section_title',
            field=models.CharField(default='Join The Elite Guild', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='rooms_section_desc',
            field=models.TextField(default='Explore our signature guest chambers designed for ultimate relaxation and comfort.'),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='rooms_section_subtitle',
            field=models.CharField(default='Premium Sanctuary', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='rooms_section_title',
            field=models.CharField(default='Rooms & Suites', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='search_modal_button_text',
            field=models.CharField(default='Search', help_text='Button text in search modal', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='search_modal_placeholder',
            field=models.CharField(default='Search room categories, dining, amenities...', help_text='Placeholder text in search input', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='search_modal_title',
            field=models.CharField(default='Search Resort', help_text='Title shown in search overlay modal', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='testimonials_section_subtitle',
            field=models.CharField(default='Guest Memoirs', max_length=150),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='testimonials_section_title',
            field=models.CharField(default='What Our Guests Say', max_length=150),
        ),
    ]
