# Generated by Django 6.0.7 on 2026-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0004_hotelsettings_facilities_section_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='footer_credits_url',
            field=models.CharField(blank=True, default='', help_text='Link URL for footer credits badge (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsettings',
            name='footer_awards_text',
            field=models.CharField(default='Powered by PocketSoft Pvt Ltd', help_text='Footer credits badge text (e.g. Powered by PocketSoft Pvt Ltd)', max_length=255),
        ),
    ]
