# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('testimonials'), validators=[core.utils.ValidateFileSize(2)])),
                ('country', models.CharField(blank=True, help_text='e.g. United Kingdom, Nepal', max_length=100, null=True)),
                ('source', models.CharField(choices=[('google', 'Google Review'), ('booking', 'Booking.com'), ('agoda', 'Agoda'), ('tripadvisor', 'Tripadvisor'), ('direct', 'Direct Guest Feedback')], default='google', max_length=20)),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('review_text', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True, help_text='Designates whether this testimonial is visible on the website')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
