# Generated by Django 6.0.7 on 2026-07-21 05:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Relative path, e.g. '/' or '/rooms/' or '/contact/'", max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=80)),
                ('meta_description', models.TextField(max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use current page URL', null=True)),
                ('header_subtitle', models.CharField(blank=True, help_text='Subtitle shown in the page header banner', max_length=150, null=True)),
                ('header_title', models.CharField(blank=True, help_text='Main title shown in the page header banner', max_length=150, null=True)),
                ('header_description', models.TextField(blank=True, help_text='Description text shown in the page header banner', null=True)),
                ('header_image', models.ImageField(blank=True, help_text='Background image for the page banner', null=True, upload_to=core.utils.UploadTo('headers'), validators=[core.utils.ValidateFileSize(2)])),
                ('og_title', models.CharField(blank=True, max_length=80, null=True)),
                ('og_description', models.TextField(blank=True, max_length=160, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to=core.utils.UploadTo('seo'), validators=[core.utils.ValidateFileSize(2)])),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary with Large Image')], default='summary_large_image', max_length=20)),
                ('structured_data', models.TextField(blank=True, help_text='Raw JSON-LD for schema markup', null=True)),
            ],
            options={
                'verbose_name': 'SEO Page Data',
                'verbose_name_plural': 'SEO Page Data',
            },
        ),
    ]
